import mongoose from "mongoose";

const todoSchema = new mongoose.Schema(
  {
    text: {
      type: String,
      required: true,
    },
    completed: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

const Todo = mongoose.model("Todo", todoSchema);
export default Todo;

//todos is the database name in the end of the URI not the collection name.. 
// The COLLECTION name is generated by Mongoose from the model name (`Todo` → `todos`)
// MongoDB creates the collection automatically when the first document is inserted.
